[project]
name = "llm-web-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "zendriver>=0.13.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
